apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
      service: rest
  template:
    metadata:
      labels:
        app: user
        service: rest
    spec:
      containers:
        - name: user
          image: ezazulhaq02/restfuluserservices:1.0
          resources:
            limits:
              memory: "252Mi"
              cpu: "1Gi"
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: rest
spec:
  type: LoadBalancer
  selector:
    app: user
    service: rest
  ports:
    - port: 8081
