# Monitoring tool plugin requests
GET http://localhost:8081/actuator HTTP/1.1

###
# Hello world Services
GET http://localhost:8081/hello-world HTTP/1.1
###
GET http://localhost:8081/hello-world-bean HTTP/1.1
###
GET http://localhost:8081/hello-world-internationalize HTTP/1.1
Accept-Language: nl

###
# Filtering response Json
GET http://localhost:8081/filter HTTP/1.1
###
GET http://localhost:8081/filter-list HTTP/1.1


###
# User Services
GET http://localhost:8081/users HTTP/1.1
Accept: application/xml
###
GET http://localhost:8081/user/4 HTTP/1.1
###
POST http://localhost:8081/users HTTP/1.1
Content-Type: application/json

{
  "name": "Yhua",
  "birthDate": "2021-07-18T14:15:37.426+00:00"
}
###
DELETE http://localhost:8081/user/2 HTTP/1.1


###
# Version controlling an API
GET http://localhost:8081/v1/person HTTP/1.1
###
GET http://localhost:8081/v2/person HTTP/1.1
